version: '3.8'

services:
  compiler-service:
    image: compiler-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compiler-container
    entrypoint: ["java", "-jar", "/compiler.jar"]
    volumes:
      - ./build/libs/compiler-0.0.1-SNAPSHOT.jar:/compiler.jar
    environment:
      - JAVA_OPTS=-Xmx512m
    ports:
      - "8080:8080"
